#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/cowbell .
docker build -t ${REPO}/cowbell:${TAG} .

echo Built ${REPO}/cowbell:${TAG}
